name = "integration-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
tail_consumers = [{ service = "alert-worker" }]

[[kv_namespaces]]
binding = "LEADS_SYNC_CACHE"
id = "5bdb23b812e54e0fbd9b70dfa25cd5db"

[[kv_namespaces]]
binding = "VMG_AUTH_CACHE"
id = "16c54f9e62cd4127a58c47ff09e775a6"

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1.0
